name: Deploy to Server

on:
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  build:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'

    - name: Install dependencies
      run: npm install

    - name: Build project
      run: npm run build

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build Docker image
      run: docker build . --file Dockerfile --tag robsonndev/robson.dev-portfolio:latest

    - name: Push Docker image
      run: docker push robsonndev/robson.dev-portfolio:latest

  deploy:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Deploy to server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: ${{ secrets.SSH_PORT }}
        script: |
          docker pull robsonndev/robson.dev-portfolio:latest
          docker-compose -f /opt/sites/robson.dev/docker-compose.yml up -d --build
